Add messages and basic shoprotation command
skycavemc/shop-rotation pull request #1
Opened 2022-09-24 13:18 UTC by NYC1809

2022-09-24 13:23 UTC, heuerleon requested changes

2022-09-24 13:23 UTC, heuerleon commented on src/main/kotlin/de/skycave/shoprotation/Enums/Message.kt
> +        return ChatColor.translateAlternateColorCodes('&', PREFIX.message + message)
This is how we used to return messages in older plugins. Where did you take that from?

2022-09-24 13:37 UTC, NYC1809 commented on src/main/kotlin/de/skycave/shoprotation/Enums/Message.kt
> +        return ChatColor.translateAlternateColorCodes('&', PREFIX.message + message)
I copied that part from MiniEvents. I will change that to the newer version.

2022-09-24 13:46 UTC, heuerleon commented on src/main/kotlin/de/skycave/shoprotation/Enums/Message.kt
> +        return ChatColor.translateAlternateColorCodes('&', PREFIX.message + message)
You can look here for reference: https://github.com/skycavemc/chest-refiller/blob/main/src/main/kotlin/de/skycave/chestrefiller/enums/Message.kt and here https://github.com/skycavemc/chest-refiller/blob/main/src/main/kotlin/de/skycave/chestrefiller/models/ChatMessage.kt

2022-09-26 21:03 UTC, heuerleon commented
Looks good!

2022-09-26 21:03 UTC, heuerleon approved these changes

2022-09-26 21:03 UTC, merged